export const ADD_GOLFS_PLAYED = "ADD_MAIN_GOLFS_PLAYED";
export const DELETE_GOLFS_PLAYED = "DELETE_MAIN_GOLFS_PLAYED";
export const RESET_GOLFS_PLAYED = "RESET_MAIN_GOLFS_PLAYED";
export const INIT_GOLFS_PLAYED = "INIT_MAIN_GOLFS_PLAYED";