export const ADD_MAIN_USER_SCORE_CARD = "ADD_MAIN_USER_SCORE_CARD";
export const DELETE_MAIN_USER_SCORE_CARD = "DELETE_MAIN_USER_SCORE_CARD";
export const RESET_MAIN_USER_SCORE_CARD = "RESET_MAIN_USER_SCORE_CARD";
export const INIT_MAIN_USER_SCORE_CARD = "INIT_MAIN_USER_SCORE_CARD";