export const ADD_GUILDS = "ADD_GUILD_LIST";
export const DELETE_GUILDS = "DELETE_GUILD_LIST";
export const RESET_GUILDS = "RESET_GUILD_LIST";
export const INIT_GUILDS = "INIT_GUILD_LIST";
export const MODIFY_GUILDS = "MODIFY_GUILD_LIST";
export const UPDATE_GUILDS = "UPDATE_GUILD_LIST";
export const UNREAD_GUILDS = "UNREAD_GUILD_LIST";
export const CHANGE_MESSAGE_UNREAD_GUILDS = "CHANGE_MESSAGE_UNREAD_GUILD_LIST";

// Nouvelles actions pour la synchronisation interne
export const UPDATE_GUILD_INFO = "UPDATE_GUILD_INFO";
export const ADD_GUILD_MEMBER = "ADD_GUILD_MEMBER";
export const REMOVE_GUILD_MEMBER = "REMOVE_GUILD_MEMBER";
export const UPDATE_GUILD_MEMBERS = "UPDATE_GUILD_MEMBERS";
export const REFRESH_GUILD_LIST = "REFRESH_GUILD_LIST";