export const WebSocketRoutes = {
  CONNECT: 0,
  CHECK_CONNECTION: 1,
  SEND_MESSAGE: 2,
  READ_MESSAGE: 3,
  START_TYPING: 4,
  STOP_TYPING: 5,
  RECEIVE_NOTIFICATION: 6,
  AUTHENTICATE: 7,
  HEARTBEAT: 8,
  SEND_ACHIEVEMENT: 9
};

export default WebSocketRoutes;
