export const ADD_TRENDS = "ADD_RECENT_MAIN_TRENDS";
export const DELETE_TRENDS = "DELETE_RECENT_MAIN_TRENDS";
export const RESET_TRENDS = "RESET_RECENT_MAIN_TRENDS";
export const INIT_TRENDS = "INIT_RECENT_MAIN_TRENDS";
export const ADD_CREATED_TRENDS = "ADD_RECENT_CREATED_TRENDS";